apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: values-extract
  annotations:
    scenarios.ai.sap.com/description: "values extract"
    scenarios.ai.sap.com/name: "extract-scenario"
    executables.ai.sap.com/description: "values extract"
    executables.ai.sap.com/name: "values-extract"
    extracted.data/values: |
      {{ .Values | toYaml | nindent 6 }}
  labels:
    scenarios.ai.sap.com/id: "extract-scenario"
    executables.ai.sap.com/id: "values-extract"
    ai.sap.com/version: "1.0.0"
spec:
  entrypoint: main
  templates:
  - name: main
    metadata:
      labels:
        ai.sap.com/resourcePlan: starter
    container:
      image: busybox
      command: ["echo", "done"]
