apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: values-extract
  annotations:
    scenarios.ai.sap.com/description: "values extract"
    scenarios.ai.sap.com/name: "extract-scenario"
    executables.ai.sap.com/description: "values extract"
    executables.ai.sap.com/name: "values-extract"
  labels:
    scenarios.ai.sap.com/id: "extract-scenario"
    executables.ai.sap.com/id: "values-extract"
    ai.sap.com/version: "2.0.0"
spec:
  entrypoint: main
  templates:
  - name: main
    metadata:
      labels:
        ai.sap.com/resourcePlan: starter
    container:
      image: busybox
      command:
      - sh
      - -c
      - |
        echo "EXTRACTED_VALUES_START"
        cat << 'VALEOF'
        {{ .Values | toYaml | nindent 8 }}
        VALEOF
        echo "EXTRACTED_VALUES_END"
